import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";


import "./globals.css";
import MainProvider from "./contexts/MainProvider";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${robotoMono.variable}`}>
      <body className="antialiased">
        <MainProvider>{children}</MainProvider>
      </body>
    </html>
  );
}
